----JP_0080_DATOS_CARGA_ARCH_y_CONCILIA

----PR_0080_CONCILIACION

--------------Define Catalogo DWH_DB----------------

SET CATALOG #PRY_DWH.V_0080_DB_DWH_DB_WRITE;

--------------Elimina Tabla Temporal----------------

DROP TABLE #PRY_DWH.V_0080_DB_DWH_DB_WRITE.#PRY_DWH.V_0080_SCH_DATOS.#PRY_DWH.V_0080_TABLA_TEMPORAL_CONCILIACION IF EXISTS;

---------------Crea Tabla Temporal------------------

--SET CATALOG #PRY_DWH.V_0080_DB_DWH_DB_WRITE;

CREATE TABLE #PRY_DWH.V_0080_DB_DWH_DB_WRITE.#PRY_DWH.V_0080_SCH_DATOS.#PRY_DWH.V_0080_TABLA_TEMPORAL_CONCILIACION AS (
	SELECT f.*, C.NOMBRE_ARCHIVO NOM_CONCI, C.TOTAL_REGISTROS_CARGADOS REG_CAR, C.TOTAL_REGISTROS_ESTADISTICAS REG_EST  
	FROM (
		SELECT 
		CASE WHEN A.FECHA_TRAFICO IS NULL THEN B.FECHA_TRAFICO ELSE A.FECHA_TRAFICO END FECHA_TRAFICO,
		CASE WHEN A.NOMBRE_ARCHIVO IS NULL THEN B.NOMBRE_ARCHIVO ELSE A.NOMBRE_ARCHIVO END NOMBRE_ARCHIVO,
		CASE WHEN B.NOMBRE_ARCHIVO IS NULL THEN 'SIN TRAFICO' 
			WHEN A.NOMBRE_ARCHIVO IS NULL THEN 'SIN ESTADISTICAS' ELSE 'N/A' END ESTADO,
		B.CANTIDAD_REGISTROS TOTAL_REGISTROS_CARGADOS,
		A.CANTIDAD_REGISTROS TOTAL_REGISTROS_ESTADISTICAS,
		CURRENT_TIMESTAMP  FECHA_ACTUALIZACION,
		CURRENT_TIMESTAMP FECHA_CREACION
		FROM (
			SELECT * FROM #PRY_DWH.V_0080_DB_DWH_DB_WRITE.#PRY_DWH.V_0080_SCH_DATOS.#PRY_DWH.V_0080_TABLA_FINAL_ESTADISTICAS
			WHERE FECHA_CREACION BETWEEN  TO_TIMESTAMP(TO_CHAR(CURRENT_DATE -15,'YYYYMMDD')||' 000000','YYYYMMDD HH24MISS')
			AND TO_TIMESTAMP(TO_CHAR(CURRENT_DATE,'YYYYMMDD')||' 235959','YYYYMMDD HH24MISS')
		) A 
		FULL OUTER JOIN (
                	SELECT * FROM #PRY_DWH.V_0080_DB_DWH_DB_WRITE.#PRY_DWH.V_0080_SCH_DATOS.#PRY_DWH.V_0080_TABLA_CONTROL_GPRS 
			WHERE FECHA_CREACION BETWEEN TO_TIMESTAMP(TO_CHAR(CURRENT_DATE -15,'YYYYMMDD')||' 000000','YYYYMMDD HH24MISS')
			AND TO_TIMESTAMP(TO_CHAR(CURRENT_DATE,'YYYYMMDD')||' 235959','YYYYMMDD HH24MISS')
		)B
		ON A.NOMBRE_ARCHIVO = B.NOMBRE_ARCHIVO      
	) F 
	LEFT JOIN #PRY_DWH.V_0080_DB_DWH_DB_WRITE.#PRY_DWH.V_0080_SCH_DATOS.#PRY_DWH.V_0080_TABLA_FINAL_CONCILIACION C 
	ON F.NOMBRE_ARCHIVO = C.NOMBRE_ARCHIVO
)
DISTRIBUTE ON RANDOM
;

-----------------Creacion Seguridad tabla conciliacion---------------

CREATE TABLE IF NOT EXISTS #PRY_DWH.V_0080_DB_DWH_DB_WRITE.#PRY_DWH.V_0080_SCH_DATOS.#PRY_DWH.V_0080_TABLA_FINAL_CONCILIACION
(
	FECHA_TRAFICO DATE,
	NOMBRE_ARCHIVO CHARACTER VARYING(60),
	ESTADO CHARACTER VARYING(16),
	TOTAL_REGISTROS_CARGADOS INTEGER,
	TOTAL_REGISTROS_ESTADISTICAS INTEGER,
	FECHA_ACTUALIZACION TIMESTAMP,
	FECHA_CREACION TIMESTAMP
)
DISTRIBUTE ON RANDOM
ORGANIZE ON (FECHA_TRAFICO, NOMBRE_ARCHIVO);

---------------- Inserta Registros Nuevos --------------------------

INSERT INTO #PRY_DWH.V_0080_DB_DWH_DB_WRITE.#PRY_DWH.V_0080_SCH_DATOS.#PRY_DWH.V_0080_TABLA_FINAL_CONCILIACION(
	SELECT
	FECHA_TRAFICO, 
	NOMBRE_ARCHIVO, 
	ESTADO, 
	TOTAL_REGISTROS_CARGADOS, 
	TOTAL_REGISTROS_ESTADISTICAS, 
	FECHA_ACTUALIZACION, 
	FECHA_CREACION 
	FROM #PRY_DWH.V_0080_DB_DWH_DB_WRITE.#PRY_DWH.V_0080_SCH_DATOS.#PRY_DWH.V_0080_TABLA_TEMPORAL_CONCILIACION
	WHERE NOM_CONCI IS NULL 
);

----------------- Actualiza Registros --------------------------- 

--SET CATALOG #PRY_DWH.V_0080_DB_DWH_DB_WRITE;

UPDATE #PRY_DWH.V_0080_DB_DWH_DB_WRITE.#PRY_DWH.V_0080_SCH_DATOS.#PRY_DWH.V_0080_TABLA_FINAL_CONCILIACION C
SET
C.FECHA_TRAFICO = T.FECHA_TRAFICO, 
C.ESTADO = T.ESTADO, 
C.TOTAL_REGISTROS_CARGADOS = T.TOTAL_REGISTROS_CARGADOS, 
C.TOTAL_REGISTROS_ESTADISTICAS = T.TOTAL_REGISTROS_ESTADISTICAS, 
C.FECHA_ACTUALIZACION = T.FECHA_ACTUALIZACION
FROM (
	SELECT 
	NOMBRE_ARCHIVO, 
	FECHA_TRAFICO, 
	ESTADO, 
	NVL(TOTAL_REGISTROS_CARGADOS,REG_CAR) TOTAL_REGISTROS_CARGADOS,
	NVL(TOTAL_REGISTROS_ESTADISTICAS,REG_EST) TOTAL_REGISTROS_ESTADISTICAS, 
	FECHA_ACTUALIZACION
	FROM #PRY_DWH.V_0080_DB_DWH_DB_WRITE.#PRY_DWH.V_0080_SCH_DATOS.#PRY_DWH.V_0080_TABLA_TEMPORAL_CONCILIACION
	WHERE NOM_CONCI IS NOT NULL 
	AND (
	NVL(TOTAL_REGISTROS_CARGADOS,NVL(REG_CAR,0)) <> NVL(REG_CAR,0) OR
	NVL(TOTAL_REGISTROS_ESTADISTICAS,NVL(REG_EST,0)) <> NVL(REG_EST,0)
	)
) T
WHERE C.NOMBRE_ARCHIVO = T.NOMBRE_ARCHIVO
;

-------------- Actualizar Estado --------------------------------------

--SET CATALOG #PRY_DWH.V_0080_DB_DWH_DB_WRITE;

UPDATE #PRY_DWH.V_0080_DB_DWH_DB_WRITE.#PRY_DWH.V_0080_SCH_DATOS.#PRY_DWH.V_0080_TABLA_FINAL_CONCILIACION
SET ESTADO = 'N/A'
WHERE TOTAL_REGISTROS_CARGADOS IS NOT NULL
AND TOTAL_REGISTROS_ESTADISTICAS IS NOT NULL 
AND ESTADO != 'N/A' 
;



